import '../models/question.dart';

/// Banco de questões fictício (mock) usado na fase N1 do Provas App.
///
/// 50 questões no total, divididas em 5 matérias (10 cada):
/// Matemática, Português, História, Geografia e Ciências.
/// Todas as questões têm 5 alternativas (A a E), no mesmo padrão
/// usado nas folhas de resposta do app.
final List<Question> questionBank = [
  // ---------------- MATEMÁTICA ----------------
  const Question(
    id: 'q001',
    subject: 'Matemática',
    statement: 'Quanto é 7 x 8?',
    alternatives: ['54', '56', '58', '64', '49'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q002',
    subject: 'Matemática',
    statement: 'Qual é o resultado de 15 + 27?',
    alternatives: ['32', '42', '52', '45', '38'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q003',
    subject: 'Matemática',
    statement: 'Qual é a raiz quadrada de 81?',
    alternatives: ['7', '8', '9', '10', '11'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q004',
    subject: 'Matemática',
    statement: 'Quanto soma a medida dos ângulos internos de um triângulo?',
    alternatives: ['90°', '180°', '270°', '360°', '120°'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q005',
    subject: 'Matemática',
    statement: 'Qual é o valor de 5 elevado ao quadrado (5²)?',
    alternatives: ['10', '15', '20', '25', '30'],
    correctIndex: 3,
  ),
  const Question(
    id: 'q006',
    subject: 'Matemática',
    statement: 'Quanto é 100 dividido por 4?',
    alternatives: ['20', '25', '30', '35', '40'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q007',
    subject: 'Matemática',
    statement: 'Qual das opções abaixo é um número primo?',
    alternatives: ['4', '6', '8', '9', '7'],
    correctIndex: 4,
  ),
  const Question(
    id: 'q008',
    subject: 'Matemática',
    statement: 'Qual é o valor de 3/4 em forma decimal?',
    alternatives: ['0,25', '0,5', '0,75', '0,8', '1,25'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q009',
    subject: 'Matemática',
    statement: 'Qual é o perímetro de um quadrado de lado igual a 5?',
    alternatives: ['10', '15', '20', '25', '30'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q010',
    subject: 'Matemática',
    statement: 'Quanto é 9 x 9?',
    alternatives: ['72', '81', '90', '99', '64'],
    correctIndex: 1,
  ),

  // ---------------- PORTUGUÊS ----------------
  const Question(
    id: 'q011',
    subject: 'Português',
    statement: 'A palavra "rapidamente" pertence a qual classe gramatical?',
    alternatives: ['Substantivo', 'Adjetivo', 'Advérbio', 'Verbo', 'Pronome'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q012',
    subject: 'Português',
    statement: 'Assinale o sinônimo de "feliz":',
    alternatives: ['Triste', 'Contente', 'Cansado', 'Irritado', 'Confuso'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q013',
    subject: 'Português',
    statement: 'Qual é o plural correto de "pão"?',
    alternatives: ['Pãos', 'Pões', 'Pães', 'Pãoes', 'Paens'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q014',
    subject: 'Português',
    statement:
        'Na frase "Choveram pérolas do céu" (falando de uma chuva), qual figura de linguagem aparece?',
    alternatives: ['Metáfora', 'Metonímia', 'Hipérbole', 'Ironia', 'Eufemismo'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q015',
    subject: 'Português',
    statement: 'Qual é o antônimo de "generoso"?',
    alternatives: ['Gentil', 'Amável', 'Mesquinho', 'Alegre', 'Educado'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q016',
    subject: 'Português',
    statement: 'Assinale a frase com erro de concordância verbal:',
    alternatives: [
      'Os menino chegou',
      'Os meninos chegaram',
      'Ela cantou bem',
      'Nós saímos cedo',
      'Eles foram embora',
    ],
    correctIndex: 0,
  ),
  const Question(
    id: 'q017',
    subject: 'Português',
    statement: 'Na frase "Maria, venha aqui.", qual é a função da vírgula?',
    alternatives: [
      'Separar orações',
      'Indicar vocativo',
      'Indicar pausa longa',
      'Substituir o ponto final',
      'Indicar dúvida',
    ],
    correctIndex: 1,
  ),
  const Question(
    id: 'q018',
    subject: 'Português',
    statement: 'Qual é o tempo verbal da palavra "cantarei"?',
    alternatives: [
      'Pretérito',
      'Presente',
      'Futuro do presente',
      'Futuro do pretérito',
      'Imperativo',
    ],
    correctIndex: 2,
  ),
  const Question(
    id: 'q019',
    subject: 'Português',
    statement: 'Qual é o gênero gramatical padrão da palavra "alface"?',
    alternatives: ['Masculino', 'Feminino', 'Ambos', 'Neutro', 'Comum de dois gêneros'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q020',
    subject: 'Português',
    statement: 'Qual das palavras abaixo é uma conjunção que indica oposição?',
    alternatives: ['E', 'Mas', 'Porque', 'Que', 'Se'],
    correctIndex: 1,
  ),

  // ---------------- HISTÓRIA ----------------
  const Question(
    id: 'q021',
    subject: 'História',
    statement: 'Em que ano ocorreu a Proclamação da República no Brasil?',
    alternatives: ['1822', '1888', '1889', '1900', '1930'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q022',
    subject: 'História',
    statement: 'Quem foi o primeiro imperador do Brasil?',
    alternatives: ['Dom Pedro I', 'Dom Pedro II', 'Dom João VI', 'Getúlio Vargas', 'Tiradentes'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q023',
    subject: 'História',
    statement: 'Em que ano foi assinada a Lei Áurea, que aboliu a escravidão no Brasil?',
    alternatives: ['1850', '1871', '1888', '1889', '1891'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q024',
    subject: 'História',
    statement: 'Qual evento é tradicionalmente associado ao fim da Idade Média?',
    alternatives: [
      'Revolução Francesa',
      'Queda de Constantinopla',
      'Independência dos EUA',
      'Reforma Protestante',
      'Guerra Fria',
    ],
    correctIndex: 1,
  ),
  const Question(
    id: 'q025',
    subject: 'História',
    statement: 'Quem foi o líder da Inconfidência Mineira?',
    alternatives: ['Tiradentes', 'Dom Pedro I', 'José Bonifácio', 'Getúlio Vargas', 'Duque de Caxias'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q026',
    subject: 'História',
    statement: 'Em que século teve início a Revolução Industrial?',
    alternatives: ['Século XVI', 'Século XVII', 'Século XVIII', 'Século XIX', 'Século XX'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q027',
    subject: 'História',
    statement: 'Qual foi um dos principais objetivos da Revolução Francesa?',
    alternatives: [
      'Expandir território',
      'Acabar com a monarquia absolutista',
      'Colonizar a América',
      'Unificar a Itália',
      'Criar a União Europeia',
    ],
    correctIndex: 1,
  ),
  const Question(
    id: 'q028',
    subject: 'História',
    statement: 'Quem proclamou a independência do Brasil, em 1822?',
    alternatives: ['Dom Pedro I', 'Dom Pedro II', 'Dom João VI', 'Tiradentes', 'Deodoro da Fonseca'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q029',
    subject: 'História',
    statement: 'Em que ano começou a Segunda Guerra Mundial?',
    alternatives: ['1914', '1929', '1939', '1945', '1950'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q030',
    subject: 'História',
    statement: 'Quem foi o primeiro presidente do Brasil?',
    alternatives: [
      'Deodoro da Fonseca',
      'Getúlio Vargas',
      'Dom Pedro II',
      'Floriano Peixoto',
      'Juscelino Kubitschek',
    ],
    correctIndex: 0,
  ),

  // ---------------- GEOGRAFIA ----------------
  const Question(
    id: 'q031',
    subject: 'Geografia',
    statement: 'Qual é o maior oceano do mundo?',
    alternatives: ['Atlântico', 'Índico', 'Pacífico', 'Ártico', 'Antártico'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q032',
    subject: 'Geografia',
    statement: 'Qual é o maior país do mundo em extensão territorial?',
    alternatives: ['Rússia', 'Canadá', 'China', 'Estados Unidos', 'Brasil'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q033',
    subject: 'Geografia',
    statement: 'Qual é a capital da Austrália?',
    alternatives: ['Sydney', 'Melbourne', 'Canberra', 'Perth', 'Brisbane'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q034',
    subject: 'Geografia',
    statement: 'Qual é o maior deserto quente do mundo?',
    alternatives: ['Saara', 'Gobi', 'Atacama', 'Deserto da Austrália', 'Kalahari'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q035',
    subject: 'Geografia',
    statement: 'Qual é tradicionalmente apontado como o rio mais longo do mundo?',
    alternatives: ['Nilo', 'Mississippi', 'Yangtzé', 'Danúbio', 'Volga'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q036',
    subject: 'Geografia',
    statement: 'Qual é o continente mais populoso do mundo?',
    alternatives: ['África', 'Ásia', 'Europa', 'América', 'Oceania'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q037',
    subject: 'Geografia',
    statement: 'Qual é a montanha mais alta do mundo?',
    alternatives: ['Everest', 'K2', 'Kilimanjaro', 'Aconcágua', 'Elbrus'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q038',
    subject: 'Geografia',
    statement: 'Qual é o menor país do mundo em área territorial?',
    alternatives: ['Mônaco', 'Vaticano', 'San Marino', 'Liechtenstein', 'Malta'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q039',
    subject: 'Geografia',
    statement: 'Em qual continente fica o Egito?',
    alternatives: ['Ásia', 'África', 'Europa', 'Oceania', 'América'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q040',
    subject: 'Geografia',
    statement: 'Qual linha imaginária divide a Terra entre hemisfério norte e sul?',
    alternatives: [
      'Meridiano de Greenwich',
      'Trópico de Câncer',
      'Linha do Equador',
      'Trópico de Capricórnio',
      'Círculo Polar Ártico',
    ],
    correctIndex: 2,
  ),

  // ---------------- CIÊNCIAS ----------------
  const Question(
    id: 'q041',
    subject: 'Ciências',
    statement: 'Qual órgão é responsável por bombear o sangue pelo corpo humano?',
    alternatives: ['Pulmão', 'Coração', 'Fígado', 'Rim', 'Estômago'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q042',
    subject: 'Ciências',
    statement: 'Qual gás os seres humanos precisam respirar para viver?',
    alternatives: ['Gás carbônico', 'Nitrogênio', 'Oxigênio', 'Hidrogênio', 'Metano'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q043',
    subject: 'Ciências',
    statement: 'Aproximadamente quantos ossos tem o corpo humano adulto?',
    alternatives: ['106', '156', '206', '256', '306'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q044',
    subject: 'Ciências',
    statement: 'Qual é considerada a menor unidade da vida?',
    alternatives: ['Célula', 'Átomo', 'Molécula', 'Tecido', 'Órgão'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q045',
    subject: 'Ciências',
    statement: 'Qual planeta do sistema solar é conhecido como "planeta vermelho"?',
    alternatives: ['Vênus', 'Marte', 'Júpiter', 'Saturno', 'Mercúrio'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q046',
    subject: 'Ciências',
    statement: 'Qual é a principal fonte de energia da Terra?',
    alternatives: ['Sol', 'Lua', 'Vento', 'Água', 'Petróleo'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q047',
    subject: 'Ciências',
    statement: 'Qual processo as plantas usam para produzir seu próprio alimento?',
    alternatives: ['Respiração', 'Fotossíntese', 'Digestão', 'Fermentação', 'Excreção'],
    correctIndex: 1,
  ),
  const Question(
    id: 'q048',
    subject: 'Ciências',
    statement: 'Em qual estado físico a água se encontra ao congelar?',
    alternatives: ['Sólido', 'Líquido', 'Gasoso', 'Plasma', 'Nenhuma das anteriores'],
    correctIndex: 0,
  ),
  const Question(
    id: 'q049',
    subject: 'Ciências',
    statement: 'Qual é o principal gás associado ao efeito estufa?',
    alternatives: ['Oxigênio', 'Nitrogênio', 'Gás carbônico', 'Hidrogênio', 'Hélio'],
    correctIndex: 2,
  ),
  const Question(
    id: 'q050',
    subject: 'Ciências',
    statement: 'Qual é o nome do processo de divisão celular que gera células idênticas?',
    alternatives: ['Meiose', 'Mitose', 'Fecundação', 'Fotossíntese', 'Fermentação'],
    correctIndex: 1,
  ),
];
